//! The Rust constructions against what Python produced.
//!
//! `mask-rs/vectors/reference.json` is generated by `generate_vectors.py` from
//! the Python implementation, and a Python-side test fails if it drifts. So a
//! failure here means this port disagrees with the reference -- which for
//! anyone holding already-masked data is indistinguishable from a changed key.

#![allow(non_snake_case)]

use num_bigint::BigUint;
use serde_json::Value;
use std::str::FromStr;
use bauta_core::KeyedHash;

fn vectors() -> Value {
    let path = concat!(env!("CARGO_MANIFEST_DIR"), "/../vectors/reference.json");
    let file = std::fs::read_to_string(path).expect("reference.json; run generate_vectors.py");

    serde_json::from_str(&file).expect("reference.json is JSON")
}

fn keyedHash(vectors: &Value) -> KeyedHash {
    KeyedHash::new(vectors["key"].as_str().unwrap(), vectors["domain"].as_str().unwrap())
}

fn bytesOf(value: &Value, field: &str) -> Vec<u8> {
    hex::decode(value[field].as_str().unwrap()).unwrap()
}

fn bigOf(value: &Value, field: &str) -> BigUint {
    BigUint::from_str(value[field].as_str().unwrap()).unwrap()
}

#[test]
fn digest_matches_python() {
    let vectors = vectors();
    let hash = keyedHash(&vectors);
    let cases = vectors["keyedHash"]["digest"].as_array().unwrap();
    assert!(!cases.is_empty());

    for case in cases {
        let got = hash.digest(&bytesOf(case, "message"), &bytesOf(case, "purpose"));
        assert_eq!(hex::encode(got), case["digest"].as_str().unwrap(), "digest of {case}");
    }
}

#[test]
fn expand_matches_python() {
    let vectors = vectors();
    let hash = keyedHash(&vectors);
    let cases = vectors["keyedHash"]["expand"].as_array().unwrap();
    assert!(!cases.is_empty());

    for case in cases {
        let length = case["length"].as_u64().unwrap() as usize;
        let got = hash.expand(&bytesOf(case, "message"), length, b"");
        assert_eq!(hex::encode(got), case["expand"].as_str().unwrap(), "expand of {case}");
    }
}

#[test]
fn below_matches_python() {
    let vectors = vectors();
    let hash = keyedHash(&vectors);
    let cases = vectors["keyedHash"]["below"].as_array().unwrap();
    assert!(!cases.is_empty());

    for case in cases {
        let got = hash.below(&bytesOf(case, "message"), &bigOf(case, "upper"), b"");
        assert_eq!(got.to_string(), case["below"].as_str().unwrap(), "below of {case}");
    }
}

#[test]
fn unit_matches_python() {
    let vectors = vectors();
    let hash = keyedHash(&vectors);
    let cases = vectors["keyedHash"]["unit"].as_array().unwrap();
    assert!(!cases.is_empty());

    for case in cases {
        // Python's repr of a float round-trips exactly, so this compares the
        // value rather than a rendering of it.
        let expected: f64 = case["unit"].as_str().unwrap().parse().unwrap();
        let got = hash.unit(&bytesOf(case, "message"), b"");
        assert_eq!(got.to_bits(), expected.to_bits(), "unit of {case}");
    }
}

#[test]
fn permute_matches_python() {
    let vectors = vectors();
    let hash = keyedHash(&vectors);
    let cases = vectors["keyedHash"]["permute"].as_array().unwrap();
    assert!(!cases.is_empty());

    for case in cases {
        let got = hash.permute(&bigOf(case, "size"), &bigOf(case, "value"), b"");
        assert_eq!(got.to_string(), case["permute"].as_str().unwrap(), "permute of {case}");
    }
}

#[test]
fn permute_is_a_bijection_on_small_domains() {
    let hash = KeyedHash::new("a-test-key-that-is-long-enough", "bijection");

    for size in 1u32..=300 {
        let domain = BigUint::from(size);
        let mut seen: Vec<u32> = (0..size)
            .map(|value| {
                let out = hash.permute(&domain, &BigUint::from(value), b"test");
                assert!(out < domain, "permute({size}, {value}) left the domain");
                u32::try_from(out).unwrap()
            })
            .collect();
        seen.sort_unstable();

        assert_eq!(seen, (0..size).collect::<Vec<_>>(), "permute is not one-to-one on {size}");
    }
}

/// The `key` strategy over the boundary corpus, refusals included.
///
/// Values Rust hands back as `Unsupported` are skipped: those are the ones the
/// Python layer masks itself, so agreeing on them is not this crate's job. The
/// count is asserted so that "unsupported" can never quietly swallow the suite.
#[test]
fn key_strategy_matches_python() {
    use bauta_core::{Charset, KeyStrategy, MaskError};

    let vectors = vectors();
    let hash = keyedHash(&vectors);
    let mut compared = 0;
    let mut handedBack = 0;

    for charset in [Charset::Alphanumeric, Charset::Digits, Charset::Hex] {
        let options = if charset == Charset::Alphanumeric {
            "key {}".to_owned()
        } else {
            format!("key {{\"charset\": \"{}\"}}", charset.name())
        };
        let cases = vectors["strategies"][&options].as_array().unwrap_or_else(|| panic!("{options} vectors"));
        let strategy = KeyStrategy::new(charset);

        for case in cases {
            let kind = case["type"].as_str().unwrap();
            let value = case["value"].as_str();

            // NULL never reaches a strategy, and bool/UUID/Decimal are the
            // Python layer's to unwrap before it calls in.
            let Some(value) = value else { continue };
            if kind != "str" && kind != "int" {
                continue;
            }

            let got = if kind == "int" {
                strategy.maskInteger(&hash, &value.parse().unwrap()).map(|masked| masked.to_string())
            } else {
                strategy.maskText(&hash, value)
            };

            match got {
                Err(MaskError::Unsupported) => handedBack += 1,
                Err(MaskError::Refused(message)) => {
                    let expected = case["message"].as_str().unwrap_or_else(|| {
                        panic!("{options}: rust refused {value:?} but python masked it as {:?}", case["masked"])
                    });
                    assert_eq!(message, expected, "{options}: refusal message for {value:?}");
                    compared += 1;
                }
                Ok(masked) => {
                    let expected = case["masked"].as_str().unwrap_or_else(|| {
                        panic!("{options}: python refused {value:?} ({:?}) but rust masked it", case["message"])
                    });
                    assert_eq!(masked, expected, "{options}: mask of {value:?}");
                    compared += 1;
                }
            }
        }
    }

    assert!(compared > 100, "only {compared} key vectors compared");
    assert!(handedBack > 0, "the non-ASCII fallback was never exercised");
    println!("key: {compared} vectors compared, {handedBack} handed back to Python");
}

/// The `fpe` strategy, including the short-value fallback to `key` and the
/// refusals `strict` produces.
#[test]
fn fpe_strategy_matches_python() {
    use bauta_core::{Charset, FpeStrategy, MaskError};

    let vectors = vectors();
    let hash = keyedHash(&vectors);
    let mut compared = 0;
    let mut handedBack = 0;

    let combinations = [
        ("fpe {}", Charset::Alphanumeric, false),
        ("fpe {\"charset\": \"hex\"}", Charset::Hex, false),
        ("fpe {\"charset\": \"digits\"}", Charset::Digits, false),
        ("fpe {\"strict\": true}", Charset::Alphanumeric, true),
    ];

    for (options, charset, strict) in combinations {
        let cases = vectors["strategies"][options].as_array().unwrap_or_else(|| panic!("{options} vectors"));
        let strategy = FpeStrategy::new(&hash, charset, strict);

        for case in cases {
            let kind = case["type"].as_str().unwrap();
            let Some(value) = case["value"].as_str() else { continue };
            if kind != "str" && kind != "int" {
                continue;
            }

            let got = if kind == "int" {
                strategy.maskInteger(&hash, &value.parse().unwrap()).map(|masked| masked.to_string())
            } else {
                strategy.maskText(&hash, value)
            };

            match got {
                Err(MaskError::Unsupported) => handedBack += 1,
                Err(MaskError::Refused(message)) => {
                    let expected = case["message"].as_str().unwrap_or_else(|| {
                        panic!("{options}: rust refused {value:?} but python masked it as {:?}", case["masked"])
                    });
                    assert_eq!(message, expected, "{options}: refusal for {value:?}");
                    compared += 1;
                }
                Ok(masked) => {
                    let expected = case["masked"].as_str().unwrap_or_else(|| {
                        panic!("{options}: python refused {value:?} ({:?}) but rust masked it", case["message"])
                    });
                    assert_eq!(masked, expected, "{options}: mask of {value:?}");
                    compared += 1;
                }
            }
        }
    }

    assert!(compared > 100, "only {compared} fpe vectors compared");
    println!("fpe: {compared} vectors compared, {handedBack} handed back to Python");
}

/// `hash`, `email` and `digits` -- Phase D's strategies.
#[test]
fn cheap_strategies_match_python() {
    use bauta_core::cheap;
    use bauta_core::MaskError;

    let vectors = vectors();
    let hash = keyedHash(&vectors);
    let mut compared = 0;

    // The canonical form of the values these are keyed on: text as UTF-8,
    // integers as plain decimal. `masking._canonical`.
    let canonical = |kind: &str, value: &str| -> Option<Vec<u8>> {
        match kind {
            "str" => Some(value.as_bytes().to_vec()),
            "int" => Some(value.as_bytes().to_vec()),
            _ => None,
        }
    };

    for (options, length, prefix) in [("hash {}", 16usize, ""), ("hash {\"length\": 20, \"prefix\": \"c_\"}", 20, "c_")] {
        for case in vectors["strategies"][options].as_array().unwrap() {
            let kind = case["type"].as_str().unwrap();
            let Some(value) = case["value"].as_str() else { continue };
            let Some(bytes) = canonical(kind, value) else { continue };

            assert_eq!(cheap::maskHash(&hash, &bytes, length, prefix), case["masked"].as_str().unwrap(),
                       "{options}: hash of {value:?}");
            compared += 1;
        }
    }

    for (options, keepDomain) in [("email {}", false), ("email {\"keepDomain\": true}", true)] {
        for case in vectors["strategies"][options].as_array().unwrap() {
            if case["type"].as_str().unwrap() != "str" { continue }
            let Some(value) = case["value"].as_str() else { continue };

            match cheap::maskEmail(&hash, value, 12, "example.test", keepDomain) {
                Err(MaskError::Unsupported) => {}
                Err(other) => panic!("{options}: unexpected refusal {other} for {value:?}"),
                Ok(masked) => {
                    assert_eq!(masked, case["masked"].as_str().unwrap(), "{options}: email of {value:?}");
                    compared += 1;
                }
            }
        }
    }

    for case in vectors["strategies"]["digits {}"].as_array().unwrap() {
        let kind = case["type"].as_str().unwrap();
        let Some(value) = case["value"].as_str() else { continue };

        let got = match kind {
            "str" => cheap::maskDigitsText(&hash, value, 0, 0),
            "int" => cheap::maskDigitsInteger(&hash, &value.parse().unwrap(), 0, 0).map(|n| n.to_string()),
            _ => continue,
        };

        match got {
            Err(MaskError::Unsupported) => {}
            Err(other) => panic!("digits: unexpected refusal {other} for {value:?}"),
            Ok(masked) => {
                assert_eq!(masked, case["masked"].as_str().unwrap(), "digits of {value:?}");
                compared += 1;
            }
        }
    }

    assert!(compared > 150, "only {compared} cheap-strategy vectors compared");
    println!("hash/email/digits: {compared} vectors compared");
}


#[test]
fn fake_strategies_match_python() {
    use bauta_core::{FakeKind, FakeLists, FakeStrategy};

    let vectors = vectors();
    let hash = keyedHash(&vectors);
    let strings = |value: &Value| -> Vec<String> { value.as_array().unwrap().iter().map(|item| item.as_str().unwrap().to_owned()).collect() };
    let listsFor = |locale: &str| -> FakeLists {
        let lists = &vectors["fakeLists"][locale];
        FakeLists {
            firstNames: strings(&lists["firstNames"]),
            lastNames: strings(&lists["lastNames"]),
            cities: strings(&lists["cities"]),
            streets: strings(&lists["streets"]),
            streetKinds: strings(&lists["streetKinds"]),
            address: lists["address"].as_str().unwrap().to_owned(),
            companySuffixes: strings(&lists["companySuffixes"]),
            companyWords: strings(&lists["companyWords"]),
        }
    };

    let mut compared = 0;
    for (name, cases) in vectors["strategies"].as_object().unwrap() {
        let Some((strategyName, options)) = name.split_once(' ') else { continue };
        let Some(kind) = FakeKind::parse(strategyName) else { continue };
        let options: Value = serde_json::from_str(options).unwrap();
        let locale = options.get("locale").and_then(Value::as_str).unwrap_or("default");
        let maxLength = options.get("maxLength").and_then(Value::as_u64).map(|length| length as usize);
        let strategy = FakeStrategy::new(kind, listsFor(locale), maxLength).unwrap();

        for case in cases.as_array().unwrap() {
            // Text and integers are keyed on their UTF-8 and decimal forms; the
            // rest (UUIDs, bools) are Python's, and so is None.
            let bytes = match case["type"].as_str().unwrap() {
                "str" | "int" => case["value"].as_str().unwrap().as_bytes().to_vec(),
                _ => continue,
            };
            assert_eq!(strategy.mask(&hash, &bytes), case["masked"].as_str().unwrap(), "{name}: {:?}", case["value"]);
            compared += 1;
        }
    }

    // Six strategies, each by default, with maxLength, and in every locale.
    assert!(compared > 2_000, "compared only {compared}");
}
