[package]
name = "bauta-rs"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lib]
name = "bauta_rs"
crate-type = ["cdylib"]

[dependencies]
bauta-core = { path = "../core" }
pyo3 = { version = "0.29", features = ["extension-module", "abi3-py310", "num-bigint"] }
num-bigint = "0.4"
