from __future__ import annotations

import base64
import datetime
import hashlib
import random
from typing import Any, Dict, List, Sequence, Tuple

from .databaseDialects import ColumnCategory


class Scramble:
    """Rewrites a table's rows so they no longer carry the original values.

    Pure row/column logic with no knowledge of any database: it works from the
    already-extracted `data`/`columns` and a `columnCategories` map of which
    columns are numbers, dates or text. Mapping a driver's raw column types onto
    those categories is DatabaseDialect.columnCategory()'s job.

    Each column gets one treatment, chosen in this order:

        defaultColumnValues -> the given constant in every row
        identifierColumns   -> left untouched
        scrambleColumns     -> values shuffled across rows
        randomColumns, or everything if allDataRandom -> regenerated by category
        anything else       -> shuffled

    Note the last line: a column the configuration never mentions is *shuffled*,
    not left alone. Only identifierColumns are preserved.

    What this does not provide, and a masking product needs:

    - Referential consistency. Masks are keyed on row position, not value, so
      the same value in two rows -- or in two tables -- masks differently, and
      joins between masked tables break.
    - Reproducibility. Shuffles and numeric/date regeneration use the unseeded
      `random` module; only text regeneration is salted and repeatable, and even
      that depends on row order, which `select *` does not guarantee.
    - Anonymization of unique columns under shuffling. A shuffle preserves the
      exact set of values, so every real email address is still in the table --
      just on a different row.
    """

    def __init__(self, job: str, data: List[Tuple[Any, ...]], columns: List[str], columnCategories: Dict[str, ColumnCategory] = {},
                 defaultColumnValues: Dict[str, Any] = {}, identifierColumns: List[str] = [],
                 scrambleColumns: List[str] = [], randomColumns: List[str] = [], allDataRandom: bool = False,
                 randomSalt: str = 'w3aK7ess') -> None:
        self.job = job
        self.data = data
        self.columns = columns
        self.columnCategories = columnCategories
        self.defaultColumnValues = defaultColumnValues
        self.identifierColumns = identifierColumns
        self.scrambleColumns = scrambleColumns
        self.randomColumns = randomColumns
        self.allDataRandom = allDataRandom
        self.randomSalt = randomSalt

        self.dataZip = zip(*self.data)
        self.dataDict: Dict[str, Sequence[Any]] = {}
        self.numberRecords = len(self.data)

    def hashString(self, nonce: int) -> bytes:
        """A salted SHA-1 digest of `nonce`, base64-encoded.

        Callers pass the row *position* as the nonce, which is why masks aren't
        referentially consistent: two rows holding the same value get different
        masks, and row N of any two tables gets the same one. The encoding is 28
        characters of [A-Za-z0-9_-] plus trailing '=' padding.
        """
        hasher = hashlib.sha1()
        hasher.update('{}{}'.format(self.randomSalt, nonce).encode('utf-8'))

        return base64.urlsafe_b64encode(hasher.digest())


    def _createRandomTextColumn(self, column: str, data: Sequence[Any]) -> None:
        """Replaces each value with a hash truncated to the column's longest value.

        Capped at the hash's 28 characters, so a longer column gets a shorter
        mask, and the output alphabet is base64's regardless of what the column
        held -- a masked email is no longer shaped like an email, so application
        code that validates the format will reject it. A column that is
        entirely NULL is left as is.
        """
        textLengths = [len(x) for x in data if x is not None]

        if textLengths:
            maxLength = max(textLengths)
            randomData = tuple(self.hashString(nonce=index)[0:maxLength].decode('ascii') for index in range(self.numberRecords))
            self.dataDict[column] = randomData
        else:
            self.dataDict[column] = data


    def _createRandomDateColumn(self, column: str, data: Sequence[Any]) -> None:
        """Replaces each value with a uniformly random instant in the column's range.

        Keeps the minimum and maximum, not the distribution. Unseeded, so each
        run differs. A column with a single distinct value, or all NULL, is left
        as is -- there is no range to draw from.
        """
        dataFilteredNone = [x for x in data if x is not None]

        if dataFilteredNone:
            minDate = min(dataFilteredNone)
            maxDate = max(dataFilteredNone)
            delta = (maxDate - minDate).total_seconds()

            if minDate == maxDate:
                self.dataDict[column] = data
            else:
                randomData = tuple(minDate + datetime.timedelta(seconds=random.randint(0, int(delta))) for _ in range(self.numberRecords))
                self.dataDict[column] = randomData

        else:
            self.dataDict[column] = data


    def _createRandomNumberColumn(self, column: str, data: Sequence[Any]) -> None:
        """Replaces each value with a uniformly random integer in the column's range.

        Integers only. random.randint rejects anything else, so this raises
        TypeError for a Decimal -- which is how oracledb returns every NUMBER
        column -- and for a float. Keeps the minimum and maximum, not the
        distribution, and is unseeded.
        """
        dataFilteredNone = [x for x in data if x is not None]

        if dataFilteredNone:
            maxNumber = max(dataFilteredNone)
            minNumber = min(dataFilteredNone)

            if maxNumber == minNumber:
                self.dataDict[column] = data
            else:
                randomData = tuple(random.randint(minNumber, maxNumber) for _ in range(self.numberRecords))
                self.dataDict[column] = randomData

        else:
            self.dataDict[column] = data


    def _scrambleColumn(self, column: str, data: Sequence[Any]) -> None:
        """Shuffles the column's values across rows.

        Preserves the exact multiset -- distribution, cardinality and NULL count
        all survive -- and breaks only which row each value belongs to. That
        makes it useful for statistical realism and weak as anonymization: on a
        unique column, every original value is still present.
        """
        dataList = list(data)
        random.shuffle(dataList)
        self.dataDict[column] = dataList


    def _iterateColumns(self) -> None:
        for column, data in zip(self.columns, self.dataZip):

            if column in self.defaultColumnValues.keys():
                self.dataDict[column] = (self.defaultColumnValues[column],) * self.numberRecords

            elif column in self.identifierColumns:
                self.dataDict[column] = data

            elif column in self.scrambleColumns:
                self._scrambleColumn(column=column, data=data)

            elif column in self.randomColumns or self.allDataRandom:

                columnCategory = self.columnCategories.get(column)

                if columnCategory == ColumnCategory.NUMBER:
                    self._createRandomNumberColumn(column=column, data=data)
                elif columnCategory == ColumnCategory.DATE:
                    self._createRandomDateColumn(column=column, data=data)
                else:
                    self._createRandomTextColumn(column=column, data=data)

            else:
                self._scrambleColumn(column=column, data=data)


    def scramble(self) -> None:
        if not self.numberRecords:
            self.dataScrambled = []
            return

        self._iterateColumns()
        self.dataScrambled = list(zip(*(self.dataDict[column] for column in self.columns)))
